import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './context/theme-context';
import {HeroProvider} from "./context/hero-provider";
import 'leaflet/dist/leaflet.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeroProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </HeroProvider>
      </body>
    </html>
  );
}

